/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface B2BSettlementInterface extends Interface {
    getFunction(nameOrSignature: "settleInvoice" | "settledInvoices" | "stablecoin"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentSettled"): EventFragment;

    encodeFunctionData(functionFragment: 'settleInvoice', values: [string, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settledInvoices', values: [string]): string;
encodeFunctionData(functionFragment: 'stablecoin', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'settleInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settledInvoices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stablecoin', data: BytesLike): Result;
  }

  
    export namespace PaymentSettledEvent {
      export type InputTuple = [invoiceId: string, buyer: AddressLike, supplier: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [invoiceId: string, buyer: string, supplier: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {invoiceId: string, buyer: string, supplier: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface B2BSettlement extends BaseContract {
    
    connect(runner?: ContractRunner | null): B2BSettlement;
    waitForDeployment(): Promise<this>;

    interface: B2BSettlementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    settleInvoice: TypedContractMethod<
      [invoiceId: string, supplier: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settledInvoices: TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >
    

    
    stablecoin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'settleInvoice'): TypedContractMethod<
      [invoiceId: string, supplier: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settledInvoices'): TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'stablecoin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'PaymentSettled'): TypedContractEvent<PaymentSettledEvent.InputTuple, PaymentSettledEvent.OutputTuple, PaymentSettledEvent.OutputObject>;

    filters: {
      
      'PaymentSettled(string,address,address,uint256,uint256)': TypedContractEvent<PaymentSettledEvent.InputTuple, PaymentSettledEvent.OutputTuple, PaymentSettledEvent.OutputObject>;
      PaymentSettled: TypedContractEvent<PaymentSettledEvent.InputTuple, PaymentSettledEvent.OutputTuple, PaymentSettledEvent.OutputObject>;
    
    };
  }